// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7CBju9rMuckQuoGjrT3e1ekilqVjIsGs',
    appId: '1:85381321443:web:077deff8810bfb215debd6',
    messagingSenderId: '85381321443',
    projectId: 'temo-ff',
    authDomain: 'temo-ff.firebaseapp.com',
    databaseURL: 'https://temo-ff-default-rtdb.firebaseio.com',
    storageBucket: 'temo-ff.firebasestorage.app',
    measurementId: 'G-S9T7VQ12FN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPoJ0OIBuLbcYzi0lzlHn58eEoNwuEZ8U',
    appId: '1:85381321443:android:58de9ace027a60fd5debd6',
    messagingSenderId: '85381321443',
    projectId: 'temo-ff',
    databaseURL: 'https://temo-ff-default-rtdb.firebaseio.com',
    storageBucket: 'temo-ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLzdUTbGLY1BvjVwxXAUiXfzNTtxMXk8M',
    appId: '1:85381321443:ios:206c17022bb77f465debd6',
    messagingSenderId: '85381321443',
    projectId: 'temo-ff',
    databaseURL: 'https://temo-ff-default-rtdb.firebaseio.com',
    storageBucket: 'temo-ff.firebasestorage.app',
    iosBundleId: 'com.example.gestionBibliotheque',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLzdUTbGLY1BvjVwxXAUiXfzNTtxMXk8M',
    appId: '1:85381321443:ios:206c17022bb77f465debd6',
    messagingSenderId: '85381321443',
    projectId: 'temo-ff',
    databaseURL: 'https://temo-ff-default-rtdb.firebaseio.com',
    storageBucket: 'temo-ff.firebasestorage.app',
    iosBundleId: 'com.example.gestionBibliotheque',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3NYA2MogwS-zM390s7Pa6JVrOI-ijyG8',
    appId: '1:85381321443:web:f4aef974b3b335215debd6',
    messagingSenderId: '85381321443',
    projectId: 'temo-ff',
    authDomain: 'temo-ff.firebaseapp.com',
    databaseURL: 'https://temo-ff-default-rtdb.firebaseio.com',
    storageBucket: 'temo-ff.firebasestorage.app',
    measurementId: 'G-J75ZWX89F8',
  );

}